FROM centos:7
WORKDIR /usr/local
COPY /usr/local/e2e-k8-lab/python-demo/helloWorld.py /usr/local/helloWorld.py
COPY /usr/local/e2e-k8-lab/python-demo/install-python3.sh /usr/local/install-python3.sh
RUN sh install-python3.sh
