apiVersion: apps/v1
kind: Deployment
metadata:
  name: boc-nodejs-demo
spec:
  selector:
    matchLabels:
      app: node
  replicas: 1
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: nodejs01
        image: node
