apiVersion: apps/v1
kind: Deployment
metadata:
  name: options-tracker-app
spec:
  selector:
    matchLabels:
      app: options-tracker-app
  replicas: 1
  template:
    metadata:
      labels:
        app: options-tracker-app
    spec:
      containers:
      - name: options-tracker-app
        image: vmwe2e/options-tracker-app-005
        ports:
          - containerPort: 8080

